"""Initial schema creation

Revision ID: 4745fd629317
Revises: 
Create Date: 2026-02-03 19:48:33.982019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4745fd629317'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_subscriptions_user_id', table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index('idx_sources_task_id', table_name='sources')
    op.drop_table('sources')
    op.drop_index('idx_usage_user_id', table_name='usage_logs')
    op.drop_table('usage_logs')
    op.drop_table('human_checkpoints')
    op.drop_table('contradictions')
    op.add_column('agent_actions', sa.Column('agent_name', sa.String(length=100), nullable=True))
    op.add_column('agent_actions', sa.Column('agent_type', sa.String(length=50), nullable=True))
    op.add_column('agent_actions', sa.Column('action', sa.String(length=100), nullable=True))
    op.add_column('agent_actions', sa.Column('input_data_json', sa.JSON(), nullable=True))
    op.add_column('agent_actions', sa.Column('output_data_json', sa.JSON(), nullable=True))
    op.add_column('agent_actions', sa.Column('tokens_used', sa.Integer(), nullable=True))
    op.add_column('agent_actions', sa.Column('cost_usd', sa.Numeric(precision=10, scale=4), nullable=True))
    op.add_column('agent_actions', sa.Column('started_at', sa.DateTime(), nullable=True))
    op.add_column('agent_actions', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.add_column('agent_actions', sa.Column('error', sa.Text(), nullable=True))
    op.alter_column('agent_actions', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('agent_actions', 'task_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('agent_actions', 'agent_id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.drop_index('idx_actions_task_id', table_name='agent_actions')
    op.create_index(op.f('ix_agent_actions_task_id'), 'agent_actions', ['task_id'], unique=False)
    op.drop_constraint('agent_actions_task_id_fkey', 'agent_actions', type_='foreignkey')
    op.create_foreign_key('fk_agent_actions_task_id', 'agent_actions', 'research_tasks', ['task_id'], ['id'])
    op.drop_column('agent_actions', 'intent')
    op.drop_column('agent_actions', 'output')
    op.drop_column('agent_actions', 'agent_role')
    op.drop_column('agent_actions', 'reasoning')
    op.drop_column('agent_actions', 'timestamp')
    op.drop_column('agent_actions', 'confidence')
    op.drop_column('agent_actions', 'action_type')
    op.add_column('research_tasks', sa.Column('description', sa.Text(), nullable=False))
    op.add_column('research_tasks', sa.Column('research_depth', sa.Enum('STANDARD', 'DEEP', name='researchdepth'), nullable=False))
    op.add_column('research_tasks', sa.Column('config_json', sa.JSON(), nullable=True))
    op.add_column('research_tasks', sa.Column('estimated_cost_usd', sa.Numeric(precision=10, scale=4), nullable=True))
    op.add_column('research_tasks', sa.Column('actual_cost_usd', sa.Numeric(precision=10, scale=4), nullable=True))
    op.add_column('research_tasks', sa.Column('tokens_used', sa.Integer(), nullable=True))
    op.add_column('research_tasks', sa.Column('output_path', sa.String(length=1000), nullable=True))
    op.add_column('research_tasks', sa.Column('error_message', sa.Text(), nullable=True))
    op.add_column('research_tasks', sa.Column('metadata_json', sa.JSON(), nullable=True))
    op.alter_column('research_tasks', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('research_tasks', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('research_tasks', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               nullable=False)
    op.alter_column('research_tasks', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('PENDING', 'RUNNING', 'PAUSED', 'COMPLETED', 'FAILED', 'CANCELLED', name='taskstatus'),
               nullable=False)
    op.alter_column('research_tasks', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               nullable=False)
    op.drop_index('idx_tasks_status', table_name='research_tasks')
    op.drop_index('idx_tasks_user_id', table_name='research_tasks')
    op.create_index(op.f('ix_research_tasks_user_id'), 'research_tasks', ['user_id'], unique=False)
    op.drop_constraint('research_tasks_user_id_fkey', 'research_tasks', type_='foreignkey')
    op.create_foreign_key('fk_research_tasks_user_id', 'research_tasks', 'users', ['user_id'], ['id'])
    op.drop_column('research_tasks', 'duration_seconds')
    op.drop_column('research_tasks', 'actual_cost')
    op.drop_column('research_tasks', 'task_type')
    op.drop_column('research_tasks', 'topic')
    op.drop_column('research_tasks', 'requirements')
    op.drop_column('research_tasks', 'estimated_cost')
    op.drop_column('research_tasks', 'result_data')
    op.add_column('users', sa.Column('full_name', sa.String(length=200), nullable=True))
    op.add_column('users', sa.Column('neon_user_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('subscription_status', sa.Enum('ACTIVE', 'PAST_DUE', 'CANCELED', 'TRIALING', 'INCOMPLETE', name='subscriptionstatus'), nullable=False))
    op.add_column('users', sa.Column('stripe_customer_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('monthly_standard_quota', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('monthly_deep_quota', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('standard_papers_this_month', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('deep_papers_this_month', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('total_tokens_this_month', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('total_cost_this_month', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('last_login', sa.DateTime(), nullable=True))
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('users', 'subscription_tier',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               type_=sa.Enum('FREE', 'PRO', 'ENTERPRISE', name='subscriptiontier'),
               nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               nullable=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_neon_user_id'), 'users', ['neon_user_id'], unique=True)
    op.create_index(op.f('ix_users_stripe_customer_id'), 'users', ['stripe_customer_id'], unique=True)
    op.create_index(op.f('ix_users_stripe_subscription_id'), 'users', ['stripe_subscription_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_stripe_subscription_id'), table_name='users')
    op.drop_index(op.f('ix_users_stripe_customer_id'), table_name='users')
    op.drop_index(op.f('ix_users_neon_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('users_email_key', 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('users', 'subscription_tier',
               existing_type=sa.Enum('FREE', 'PRO', 'ENTERPRISE', name='subscriptiontier'),
               server_default=sa.text("'free'::character varying"),
               type_=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.drop_column('users', 'last_login')
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'total_cost_this_month')
    op.drop_column('users', 'total_tokens_this_month')
    op.drop_column('users', 'deep_papers_this_month')
    op.drop_column('users', 'standard_papers_this_month')
    op.drop_column('users', 'monthly_deep_quota')
    op.drop_column('users', 'monthly_standard_quota')
    op.drop_column('users', 'stripe_subscription_id')
    op.drop_column('users', 'stripe_customer_id')
    op.drop_column('users', 'subscription_status')
    op.drop_column('users', 'neon_user_id')
    op.drop_column('users', 'full_name')
    op.add_column('research_tasks', sa.Column('result_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('research_tasks', sa.Column('estimated_cost', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=True))
    op.add_column('research_tasks', sa.Column('requirements', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('research_tasks', sa.Column('topic', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('research_tasks', sa.Column('task_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('research_tasks', sa.Column('actual_cost', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=True))
    op.add_column('research_tasks', sa.Column('duration_seconds', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint('fk_research_tasks_user_id', 'research_tasks', type_='foreignkey')
    op.create_foreign_key('research_tasks_user_id_fkey', 'research_tasks', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_research_tasks_user_id'), table_name='research_tasks')
    op.create_index('idx_tasks_user_id', 'research_tasks', ['user_id'], unique=False)
    op.create_index('idx_tasks_status', 'research_tasks', ['status'], unique=False)
    op.alter_column('research_tasks', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               nullable=True)
    op.alter_column('research_tasks', 'status',
               existing_type=sa.Enum('PENDING', 'RUNNING', 'PAUSED', 'COMPLETED', 'FAILED', 'CANCELLED', name='taskstatus'),
               type_=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('research_tasks', 'title',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('research_tasks', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('research_tasks', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.drop_column('research_tasks', 'metadata_json')
    op.drop_column('research_tasks', 'error_message')
    op.drop_column('research_tasks', 'output_path')
    op.drop_column('research_tasks', 'tokens_used')
    op.drop_column('research_tasks', 'actual_cost_usd')
    op.drop_column('research_tasks', 'estimated_cost_usd')
    op.drop_column('research_tasks', 'config_json')
    op.drop_column('research_tasks', 'research_depth')
    op.drop_column('research_tasks', 'description')
    op.add_column('agent_actions', sa.Column('action_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('agent_actions', sa.Column('confidence', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('agent_actions', sa.Column('timestamp', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('agent_actions', sa.Column('reasoning', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('agent_actions', sa.Column('agent_role', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('agent_actions', sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('agent_actions', sa.Column('intent', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint('fk_agent_actions_task_id', 'agent_actions', type_='foreignkey')
    op.create_foreign_key('agent_actions_task_id_fkey', 'agent_actions', 'research_tasks', ['task_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_agent_actions_task_id'), table_name='agent_actions')
    op.create_index('idx_actions_task_id', 'agent_actions', ['task_id'], unique=False)
    op.alter_column('agent_actions', 'agent_id',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('agent_actions', 'task_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('agent_actions', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.drop_column('agent_actions', 'error')
    op.drop_column('agent_actions', 'completed_at')
    op.drop_column('agent_actions', 'started_at')
    op.drop_column('agent_actions', 'cost_usd')
    op.drop_column('agent_actions', 'tokens_used')
    op.drop_column('agent_actions', 'output_data_json')
    op.drop_column('agent_actions', 'input_data_json')
    op.drop_column('agent_actions', 'action')
    op.drop_column('agent_actions', 'agent_type')
    op.drop_column('agent_actions', 'agent_name')
    op.create_table('contradictions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('source_a_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('source_b_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('contradiction_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('severity', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('resolved', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['source_a_id'], ['sources.id'], name='contradictions_source_a_id_fkey'),
    sa.ForeignKeyConstraint(['source_b_id'], ['sources.id'], name='contradictions_source_b_id_fkey'),
    sa.ForeignKeyConstraint(['task_id'], ['research_tasks.id'], name='contradictions_task_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='contradictions_pkey')
    )
    op.create_table('human_checkpoints',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('checkpoint_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('resolved_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('decision', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('human_feedback', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['research_tasks.id'], name='human_checkpoints_task_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='human_checkpoints_pkey')
    )
    op.create_table('usage_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('task_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('tokens_used', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cost', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=True),
    sa.Column('model_used', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['research_tasks.id'], name='usage_logs_task_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='usage_logs_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='usage_logs_pkey')
    )
    op.create_index('idx_usage_user_id', 'usage_logs', ['user_id'], unique=False)
    op.create_table('sources',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('authors', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('publication', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('doi', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('credibility', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('verified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['research_tasks.id'], name='sources_task_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='sources_pkey')
    )
    op.create_index('idx_sources_task_id', 'sources', ['task_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('stripe_customer_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('stripe_subscription_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('plan_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('cancelled_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('current_period_end', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='subscriptions_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='subscriptions_pkey')
    )
    op.create_index('idx_subscriptions_user_id', 'subscriptions', ['user_id'], unique=False)
    # ### end Alembic commands ###
