"""Initial schema creation with users, usage records, and research tasks

Revision ID: 0b4e2f1b4683
Revises: 
Create Date: 2026-03-24 17:43:34.948532

"""
from typing import Sequence, Union
import uuid

from alembic import op
import sqlalchemy as sa
from sqlalchemy.types import TypeDecorator, CHAR
from sqlalchemy.dialects.postgresql import UUID as PG_UUID


# Define GUID TypeDecorator locally to avoid external dependencies
class GUID(TypeDecorator):
    """Platform-independent GUID type for storing UUID values.
    
    Uses CHAR(32) on non-PostgreSQL and PostgreSQL UUID type on PostgreSQL.
    """
    
    impl = CHAR
    cache_ok = True

    def load_dialect_impl(self, dialect):
        """Use native UUID type on PostgreSQL."""
        if dialect.name == 'postgresql':
            return dialect.type_descriptor(PG_UUID())
        return dialect.type_descriptor(CHAR(32))

    def process_bind_param(self, value, dialect):
        """Convert UUID to string for storage."""
        if value is None:
            return value
        
        if isinstance(value, uuid.UUID):
            if dialect.name == 'postgresql':
                return str(value)
            else:
                return value.hex
        
        if isinstance(value, str):
            if dialect.name == 'postgresql':
                return value
            else:
                return uuid.UUID(value).hex
        
        return value

    def process_result_value(self, value, dialect):
        """Convert stored value back to UUID.
        
        PostgreSQL's native UUID type returns uuid.UUID objects directly,
        while other databases return strings. This method handles both cases.
        """
        if value is None:
            return value
        
        # PostgreSQL native UUID returns uuid.UUID directly
        if isinstance(value, uuid.UUID):
            return value
        
        # Other databases return strings or hex values
        if isinstance(value, str):
            return uuid.UUID(value)
        
        return value


# revision identifiers, used by Alembic.
revision: str = '0b4e2f1b4683'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.String(length=255), nullable=True),
    sa.Column('details_json', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_id'), 'audit_logs', ['resource_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_table('dodo_webhook_events',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('dodo_event_id', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('data_json', sa.JSON(), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dodo_webhook_events_dodo_event_id'), 'dodo_webhook_events', ['dodo_event_id'], unique=True)
    op.create_table('users',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('neon_user_id', sa.String(length=255), nullable=True),
    sa.Column('subscription_tier', sa.Enum('FREE', 'PRO', 'ENTERPRISE', name='subscriptiontier'), nullable=False),
    sa.Column('subscription_status', sa.Enum('ACTIVE', 'PAST_DUE', 'CANCELED', 'TRIALING', 'INCOMPLETE', name='subscriptionstatus'), nullable=False),
    sa.Column('dodo_customer_id', sa.String(length=255), nullable=True),
    sa.Column('dodo_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('monthly_standard_quota', sa.Integer(), nullable=True),
    sa.Column('monthly_deep_quota', sa.Integer(), nullable=True),
    sa.Column('standard_papers_this_month', sa.Integer(), nullable=True),
    sa.Column('deep_papers_this_month', sa.Integer(), nullable=True),
    sa.Column('total_tokens_this_month', sa.Integer(), nullable=True),
    sa.Column('total_cost_this_month', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_dodo_customer_id'), 'users', ['dodo_customer_id'], unique=True)
    op.create_index(op.f('ix_users_dodo_subscription_id'), 'users', ['dodo_subscription_id'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_neon_user_id'), 'users', ['neon_user_id'], unique=True)
    op.create_table('email_verifications',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('user_id', GUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('last_sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_email_verifications_email'), 'email_verifications', ['email'], unique=False)
    op.create_index(op.f('ix_email_verifications_token'), 'email_verifications', ['token'], unique=True)
    op.create_index(op.f('ix_email_verifications_user_id'), 'email_verifications', ['user_id'], unique=True)
    op.create_table('payments',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('user_id', GUID(), nullable=False),
    sa.Column('dodo_payment_id', sa.String(length=255), nullable=True),
    sa.Column('dodo_session_id', sa.String(length=255), nullable=True),
    sa.Column('amount_usd', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('subscription_tier', sa.Enum('FREE', 'PRO', 'ENTERPRISE', name='subscriptiontier'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dodo_session_id')
    )
    op.create_index(op.f('ix_payments_dodo_payment_id'), 'payments', ['dodo_payment_id'], unique=True)
    op.create_index(op.f('ix_payments_user_id'), 'payments', ['user_id'], unique=False)
    op.create_table('research_tasks',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('user_id', GUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('research_depth', sa.Enum('STANDARD', 'DEEP', name='researchdepth'), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'PAUSED', 'COMPLETED', 'FAILED', 'CANCELLED', name='taskstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('estimated_cost_usd', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('actual_cost_usd', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('output_path', sa.String(length=1000), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('final_state_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_tasks_user_id'), 'research_tasks', ['user_id'], unique=False)
    op.create_table('usage_records',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('user_id', GUID(), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('standard_papers', sa.Integer(), nullable=True),
    sa.Column('deep_papers', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('total_cost_usd', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_records_user_id'), 'usage_records', ['user_id'], unique=False)
    op.create_table('agent_actions',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('task_id', GUID(), nullable=False),
    sa.Column('agent_id', GUID(), nullable=True),
    sa.Column('agent_name', sa.String(length=100), nullable=True),
    sa.Column('agent_type', sa.String(length=50), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=True),
    sa.Column('input_data_json', sa.JSON(), nullable=True),
    sa.Column('output_data_json', sa.JSON(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['research_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_actions_task_id'), 'agent_actions', ['task_id'], unique=False)
    op.create_table('research_checkpoints',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('task_id', GUID(), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('agent_type', sa.String(length=50), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('state_snapshot_json', sa.JSON(), nullable=False),
    sa.Column('status_before', sa.String(length=50), nullable=True),
    sa.Column('status_after', sa.String(length=50), nullable=True),
    sa.Column('duration_seconds', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('is_resumable', sa.Boolean(), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['research_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_checkpoints_task_id'), 'research_checkpoints', ['task_id'], unique=False)
    op.create_table('token_usage_logs',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('task_id', GUID(), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('input_preview', sa.String(length=500), nullable=True),
    sa.Column('output_preview', sa.String(length=500), nullable=True),
    sa.Column('duration_seconds', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['research_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_token_usage_logs_task_id'), 'token_usage_logs', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_token_usage_logs_task_id'), table_name='token_usage_logs')
    op.drop_table('token_usage_logs')
    op.drop_index(op.f('ix_research_checkpoints_task_id'), table_name='research_checkpoints')
    op.drop_table('research_checkpoints')
    op.drop_index(op.f('ix_agent_actions_task_id'), table_name='agent_actions')
    op.drop_table('agent_actions')
    op.drop_index(op.f('ix_usage_records_user_id'), table_name='usage_records')
    op.drop_table('usage_records')
    op.drop_index(op.f('ix_research_tasks_user_id'), table_name='research_tasks')
    op.drop_table('research_tasks')
    op.drop_index(op.f('ix_payments_user_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_dodo_payment_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_email_verifications_user_id'), table_name='email_verifications')
    op.drop_index(op.f('ix_email_verifications_token'), table_name='email_verifications')
    op.drop_index(op.f('ix_email_verifications_email'), table_name='email_verifications')
    op.drop_table('email_verifications')
    op.drop_index(op.f('ix_users_neon_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_dodo_subscription_id'), table_name='users')
    op.drop_index(op.f('ix_users_dodo_customer_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_dodo_webhook_events_dodo_event_id'), table_name='dodo_webhook_events')
    op.drop_table('dodo_webhook_events')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    
    # Drop PostgreSQL enum types (PostgreSQL only)
    if op.get_bind().dialect.name == 'postgresql':
        op.execute('DROP TYPE IF EXISTS subscriptiontier CASCADE')
        op.execute('DROP TYPE IF EXISTS subscriptionstatus CASCADE')
        op.execute('DROP TYPE IF EXISTS researchdepth CASCADE')
        op.execute('DROP TYPE IF EXISTS taskstatus CASCADE')
    # ### end Alembic commands ###
